---
version: "3.9"

services:
  lint:
    image: ghcr.io/super-linter/super-linter:latest
    volumes:
      - .:/tmp/lint
    environment:
      - RUN_LOCAL=true
      - DEFAULT_BRANCH=main
      - FILTER_REGEX_EXCLUDE=CHANGELOG.md
      - VALIDATE_ALL_CODEBASE=true
      - VALIDATE_PYTHON_ISORT=false

  fix:
    extends: lint
    environment:
      - FIX_HTML_PRETTIER=true
      - FIX_JSON_PRETTIER=true
      - FIX_JSON=true
      - FIX_JSONC=true
      - FIX_JSONC_PRETTIER=true
      - FIX_MARKDOWN_PRETTIER=true
      - FIX_MARKDOWN=true
      - FIX_PYTHON_BLACK=true
      - FIX_PYTHON_PYINK=true
      - FIX_PYTHON_RUFF=true
      - FIX_SHELL_SHFMT=true
      - FIX_YAML_PRETTIER=true
